vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        skill_image:
            uri_prefix: /images/skills
            upload_destination: '%kernel.project_dir%/public/images/skills'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        media_image:
            uri_prefix: /images/media
            upload_destination: '%kernel.project_dir%/public/images/media'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        project_image:
            uri_prefix: /images/projects
            upload_destination: '%kernel.project_dir%/public/images/projects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        education_image:
            uri_prefix: /images/educations
            upload_destination: '%kernel.project_dir%/public/images/educations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        award_image:
            uri_prefix: /images/awards
            upload_destination: '%kernel.project_dir%/public/images/awards'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            